Editors 225
PalladioSimulator/Palladio-Editors-Sirius pull request #40
Opened 2022-07-12 14:49 UTC by jolehmann

Die Ankerpunkte der Assembly Diagramm Konektoren wurden entsprechend nachfolgender Grafik umgesetzt.

Die Anpassungen befinden sich in:
org.palladiosimulator.editors.sirius.custom.style.styleconfiguration
org.palladiosimulator.editors.sirius.custom.style.styleconfiguration.anchorProvider
org.palladiosimulator.editors.sirius.custom.style.styleconfiguration.provider

Zusätzlich wurden die Grafiken der Nodes zentriert.

![Anchorpoints](https://user-images.githubusercontent.com/77493291/174072534-26f9e6a4-e5c4-480b-8614-386a5156d592.png)

2022-07-15 08:38 UTC, majuwa requested changes
It works mostly fine for my test cases, but I have some small change request:
- There is some problem with the event provided connectors, at least under Linux it looks like they are some pixels of (will add later an image)
![image](https://user-images.githubusercontent.com/2059629/179187242-472a1c48-9fa4-4263-a80c-b6e92c7e449f.png)
![image](https://user-images.githubusercontent.com/2059629/179187061-c51b680c-1e84-472a-a317-51b389628762.png)
- It might be a good idea to remove also the white background from the required connectors, unless there is a specific reason (they had these originally already, but since this pr modifies them, we could just fix this problem, too)
- There seems to be a problem with the [Palladio-CodingConventions](https://sdqweb.ipd.kit.edu/wiki/Palladio_Coding_Conventions) (e.g. indentation with tabs instead of whitespaces). It might be good to use the Clean-Up-Function on all the newly added classes and use the checkstyle for the new classes. I added also some comments regarding the naming convention in the source code.

2022-07-15 08:38 UTC, majuwa commented on bundles/org.palladiosimulator.editors.sirius.custom.style/src/org/palladiosimulator/editors/sirius/custom/style/styleconfiguration/anchorProvider/AbstractOrientedAnchor.java
> +	private final Map<Orientation, Translation> TRANSLATION_CALCULATORS = createTranslationCalculators();
please use cameCase in that case, since it is not a static variable

2022-08-02 12:21 UTC, jolehmann commented
Regarding the Requests:
1) The position of the arrows is unfortunately due to the arrow thickness rendered by Sirius. If you look at the marker when the arrow is selected, it is in the right place. Even if you manually set the thickness of the connector to zero, the tip is in the right place.
![Screenshot (1136)](https://user-images.githubusercontent.com/77493291/182371961-4e3fed6b-f080-4e0f-aa5c-d4026357194d.png)
![Screenshot (1137)](https://user-images.githubusercontent.com/77493291/182371977-93088d16-9165-4613-991f-7ac9f1e9d5b2.png)

2) The deletion of the white background is another Jira issue and belongs to EDITORS-278, but this issue will also be worked on during the practical course, which means that the adjustment will take place there.

3) Package name and variable name in camelCase are adapted in the upcoming commit. Tabbed indentation like this is throughout the entire Sirius project, not just in the new classes. Should this really be adjusted?

2022-08-03 08:15 UTC, jolehmann commented
After the last commit, all new classes are now conform to the palladio codeconventions.

2022-08-04 06:28 UTC, majuwa commented
I have a question regarding the anchor point. Would it be possible to calculate the offset of the thickness and then use a new anchor point, since you already individually calculate them as far as I understand the code. I'm not sure whether this is actually a good idea, but it could fix this non-center arrow.

2022-08-04 09:49 UTC, jolehmann commented
The idea sounded like a good one and I just wrote a decorator that slides the tip back on the edge with PIXEL_OFFSET as follows:

![Screenshot (1143)](https://user-images.githubusercontent.com/77493291/182814581-de9f51cf-94e3-41b5-8b3b-8b1391f80d6f.png)

"reference" is the point where the arrow comes from, "anchorPoint" is the usually calculated anchor.

The problem is that the display depends on the scaling of the editor, that means with PIXEL_OFFSET = 10 the whole thing looks good in full zoom, but if you are further away, the offset is much too big. Because the anchor point is calculated independently of the editor, only via the diagram, you unfortunately have no access to the scaling during calculation.

<img src="https://user-images.githubusercontent.com/77493291/182815901-842a9b1c-f793-411f-9a13-e9bee63a360f.png" width="400"><img src="https://user-images.githubusercontent.com/77493291/182815932-926a0670-4fe3-4ab9-b479-7e4deddd8ef9.png" width="400">


I am therefore think to leave it at the old state. Or do you have another idea?

2022-08-04 10:42 UTC, jolehmann commented
Update:

It is indeed possible, I only had to translate the points temporarily into the coordinate system of the parent figure. With a PIXEL_OFFSET = 2, which also corresponds to the set Sirius Edge Size, it looks good now.

![Screenshot (1145)](https://user-images.githubusercontent.com/77493291/182827672-88702d1a-4e1a-4d6e-b3bd-9056af922d3c.png)

Now the only question is to include the whole thing cleanly in the class structure, is it enough to include this as a new class OrientedFixpointOffsetAnchorProvider, which is then used by the sink node?

2022-08-05 06:45 UTC, majuwa commented
I think the changes in your branch look fine. In some cases there is still some offset visible, but that might be a Linux problem. But it is already much better than before. Therefore, I would suggest adding the changes to the pull request.

2022-08-09 08:36 UTC, majuwa approved these changes
works for me

2022-08-09 08:40 UTC, merged